name: release
on:
  push:
    branches:
      - main
      - develop

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'
    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7
    # QEMU
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v1
    # Buildx
    - name: Setup Docker BuildX
      uses: docker/setup-buildx-action@v1
    # Docker login
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CONTAINER_REGISTRY_PAT }}
    # Login, build & publish docker image
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        file: Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/trove:latest
          ghcr.io/${{ github.repository_owner }}/trove:${{ steps.gitversion.outputs.NuGetVersionV2 }}
        build-args: RELEASE_VERSION=${{ steps.gitversion.outputs.NuGetVersionV2 }}
        platforms: linux/amd64
